// external imports
// Web framework for Node.js
const express = require("express");
// ODM (Object Document Mapper) provides schema validation and DB operations.
// Note relational data bases would use a ORM (Object Relational Mapper).
const mongoose = require("mongoose");
// This package will allow requests from the client to the server to be processed.
const cors = require("cors");
// If the request doesn’t pass the described validation, celebrate will pass it
//  on to the error handler but not to the controller. celebrate has a special
// errors() middleware for sending errors to the client.
const { errors } = require("celebrate");
// When you use the dotenv package and add require('dotenv').config() to your code,
// you gain access to this special object called process.env. Here's what happens:
// - Environmental variables are stored outside your application code.
// - process.env acts like a bridge to access these variables.
// - Your application can read values like passwords or API keys without hardcoding them.
require("dotenv").config();

// internal imports
const indexRouter = require("./routes");
const errorHandler = require("./middlewares/error-handler");
const { requestLogger, errorLogger } = require("./middlewares/logger");

// Creating an 'instance' of an express app.
const app = express();

/* Connecting my express server to the data base. Note MongoDB uses 'lazy creation'
and won't technically create the database until I save a document on it.
127.0.0.1 is the same as localhost but works universally on all computers. */
mongoose
  .connect("mongodb://127.0.0.1:27017/wtwr_db")
  // mongoose.connect returns a promise so we can add a notification when it connects
  // or an error if there's a problem.
  .then(() => console.log("Connected to MongoDB"))
  .catch((e) => {
    console.error(e);
  });

app.use(cors());
// Place this middleware before routes
// Middleware to parse JSON from client when creating resources
app.use(express.json());
// Middleware to parse Content-Type: application/x-www-form-urlencoded (HTML form)
app.use(express.urlencoded({ extended: true })); // Technically don't need this middleware for this app

// Enable the request logger before all route handlers.
app.use(requestLogger);

// Entry point for routes. Otherwise I'd have to require all different routes here
// like userRoutes and clothingItemRoutes ect.
app.use("/", indexRouter);

// Winston error logs
// The error logger needs to be enabled after the route handlers and before the error handlers.
app.use(errorLogger);

// Celebrate error handler.
// The errors() middleware will only handle errors generated by celebrate.
// It will pass all other errors further, where the centralized error handler will catch them.
app.use(errors());

// Centralized error handling middleware.
app.use(errorHandler);

// Creating an environment variable for port with a default port to run the server on.
const { PORT = 3001 } = process.env;

// Creating the server and listening for requests on the environment port.
app.listen(PORT, () => {
  console.log(`Listening on port: ${PORT}`);
});
